"""Internal mixin for InfrastructureView.

This file is generated by refactoring Source/InfrastructureView.py to keep the main widget
small and focused.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PyQt6.QtCore import Qt, QPointF, QRectF, QTimer, QEvent
from PyQt6.QtGui import QBrush, QColor, QPainterPath, QPen
from PyQt6.QtWidgets import (
    QDialog,
    QGraphicsEllipseItem,
    QGraphicsItem,
    QGraphicsPathItem,
    QGraphicsRectItem,
    QGraphicsSimpleTextItem,
    QGraphicsView,
    QMessageBox,
)

from Source.infra_items import NodeItem, TrackItem, TimingPointItem, StoppingLocationItem
from Source.infra_models import Node, Track, TimingPoint, StoppingLocation, SchematicSegment
from Source.infra_ui import TimingConstraintDialog


class InfrastructureViewLayoutsMixin:
    def _path_from_points(self, pts: List[QPointF]) -> QPainterPath:
        path = QPainterPath(pts[0])
        for p in pts[1:]:
            path.lineTo(p)
        return path

    def _axis_polyline_with_45deg_corners(self, pts: List[QPointF], bevel: float) -> List[QPointF]:
        """
        Replace 90° corners in an axis-aligned polyline with 45° chamfers.

        This is used in schematic mode to make paths look more like railway schematics.
        """
        if len(pts) < 3:
            return pts

        cleaned: List[QPointF] = [pts[0]]
        for p in pts[1:]:
            if (p.x() - cleaned[-1].x()) ** 2 + (p.y() - cleaned[-1].y()) ** 2 > 1e-12:
                cleaned.append(p)
        if len(cleaned) < 3:
            return cleaned

        out: List[QPointF] = [cleaned[0]]
        for prev, cur, nxt in zip(cleaned[:-2], cleaned[1:-1], cleaned[2:]):
            dx1 = float(cur.x() - prev.x())
            dy1 = float(cur.y() - prev.y())
            dx2 = float(nxt.x() - cur.x())
            dy2 = float(nxt.y() - cur.y())

            # Skip if straight / degenerate.
            if (abs(dx1) <= 1e-9 and abs(dy1) <= 1e-9) or (abs(dx2) <= 1e-9 and abs(dy2) <= 1e-9):
                out.append(cur)
                continue
            if abs(dx1) <= 1e-9 and abs(dx2) <= 1e-9:
                out.append(cur)
                continue
            if abs(dy1) <= 1e-9 and abs(dy2) <= 1e-9:
                out.append(cur)
                continue

            # Only chamfer axis-aligned right angles.
            axis1 = (abs(dx1) <= 1e-9) != (abs(dy1) <= 1e-9)
            axis2 = (abs(dx2) <= 1e-9) != (abs(dy2) <= 1e-9)
            if not (axis1 and axis2):
                out.append(cur)
                continue
            if (abs(dx1) <= 1e-9 and abs(dy2) <= 1e-9) or (abs(dy1) <= 1e-9 and abs(dx2) <= 1e-9):
                pass
            else:
                out.append(cur)
                continue

            len1 = abs(dx1) + abs(dy1)
            len2 = abs(dx2) + abs(dy2)
            b = min(float(bevel), float(len1) * 0.49, float(len2) * 0.49)
            if b <= 0.5:
                out.append(cur)
                continue

            ux1 = 0.0 if abs(dx1) <= 1e-9 else (1.0 if dx1 > 0 else -1.0)
            uy1 = 0.0 if abs(dy1) <= 1e-9 else (1.0 if dy1 > 0 else -1.0)
            ux2 = 0.0 if abs(dx2) <= 1e-9 else (1.0 if dx2 > 0 else -1.0)
            uy2 = 0.0 if abs(dy2) <= 1e-9 else (1.0 if dy2 > 0 else -1.0)

            p_in = QPointF(cur.x() - ux1 * b, cur.y() - uy1 * b)
            p_out = QPointF(cur.x() + ux2 * b, cur.y() + uy2 * b)
            out.append(p_in)
            out.append(p_out)

        out.append(cleaned[-1])

        # Remove any accidental duplicates created by tiny bevels.
        final: List[QPointF] = [out[0]]
        for p in out[1:]:
            if (p.x() - final[-1].x()) ** 2 + (p.y() - final[-1].y()) ** 2 > 1e-12:
                final.append(p)
        return final

    def _offset_polyline(self, pts: List[QPointF], offset: float) -> List[QPointF]:
        """
        Approximate parallel polyline by offsetting vertices along the local normal.

        Used in Plan view to draw multiple parallel tracks per schematic segment.
        """
        if len(pts) < 2 or abs(float(offset)) <= 1e-9:
            return list(pts)

        # Per-segment unit normals.
        normals: List[Tuple[float, float]] = []
        for a, b in zip(pts[:-1], pts[1:]):
            dx = float(b.x() - a.x())
            dy = float(b.y() - a.y())
            l = math.hypot(dx, dy)
            if l <= 1e-9:
                normals.append((0.0, 0.0))
            else:
                ux = dx / l
                uy = dy / l
                normals.append((-uy, ux))

        out: List[QPointF] = []
        n = len(pts)
        for i, p in enumerate(pts):
            if i == 0:
                nx, ny = normals[0]
            elif i == n - 1:
                nx, ny = normals[-1]
            else:
                n1x, n1y = normals[i - 1]
                n2x, n2y = normals[i]
                nx = n1x + n2x
                ny = n1y + n2y
                ln = math.hypot(nx, ny)
                if ln <= 1e-9:
                    nx, ny = n1x, n1y
                else:
                    nx /= ln
                    ny /= ln
            out.append(QPointF(p.x() + nx * offset, p.y() + ny * offset))
        return out

    def _sample_path_points(self, path: QPainterPath, steps: int = 120) -> List[QPointF]:
        steps = max(8, int(steps))
        return [path.pointAtPercent(i / steps) for i in range(steps + 1)]

    def _geographic_polyline_points_for_track(self, tr: Track) -> Optional[List[QPointF]]:
        if tr.source not in self._nodes or tr.target not in self._nodes:
            return None
        src = self._node_positions.get(tr.source)
        tgt = self._node_positions.get(tr.target)
        if src is None or tgt is None:
            return None
        pts = [QPointF(src)]
        pts += [QPointF(x, y) for (x, y) in tr.shaping_points]
        pts.append(QPointF(tgt))
        return pts

    def _topological_track_path(self, tr: Track) -> Optional[QPainterPath]:
        src = self._node_positions.get(tr.source)
        tgt = self._node_positions.get(tr.target)
        if src is None or tgt is None:
            return None

        lane_y = float(self._topo_track_offset_y.get(tr.id, 0.0))
        dx = tgt.x() - src.x()
        if abs(dx) <= 1e-6 or abs(lane_y) <= 1e-6:
            path = QPainterPath(QPointF(src))
            path.lineTo(QPointF(tgt))
            return path

        sign = 1.0 if dx >= 0.0 else -1.0
        abs_dx = abs(dx)
        ramp = min(90.0, abs_dx * 0.22)
        if ramp * 2.0 > abs_dx:
            ramp = abs_dx / 2.0

        p0 = QPointF(src)
        p3 = QPointF(tgt)
        p1 = QPointF(p0.x() + sign * ramp * 0.5, p0.y())
        p2 = QPointF(p0.x() + sign * ramp * 0.5, lane_y)
        p4 = QPointF(p0.x() + sign * ramp, lane_y)

        p5 = QPointF(p3.x() - sign * ramp, lane_y)
        p6 = QPointF(p3.x() - sign * ramp * 0.5, lane_y)
        p7 = QPointF(p3.x() - sign * ramp * 0.5, p3.y())

        path = QPainterPath(p0)
        path.cubicTo(p1, p2, p4)
        if (sign > 0 and p4.x() < p5.x()) or (sign < 0 and p4.x() > p5.x()):
            path.lineTo(p5)
        path.cubicTo(p6, p7, p3)
        return path

    def _track_to_path(self, tr: Track) -> Optional[QPainterPath]:
        cached = self._track_render_paths.get(tr.id)
        if cached is not None:
            return cached

        if self._layout_mode == "topological":
            path = self._topological_track_path(tr)
        else:
            pts = self._geographic_polyline_points_for_track(tr)
            path = self._path_from_points(pts) if pts else None

        if path is not None:
            self._track_render_paths[tr.id] = path
        return path

    def _polyline_points_for_track(self, tr: Track) -> Optional[List[QPointF]]:
        cached = self._track_render_polylines.get(tr.id)
        if cached is not None:
            return cached

        if self._layout_mode == "geographic":
            pts = self._geographic_polyline_points_for_track(tr)
        else:
            path = self._track_to_path(tr)
            pts = self._sample_path_points(path) if path is not None else None

        if pts is not None:
            self._track_render_polylines[tr.id] = pts
        return pts

    def _point_along_polyline(self, pts: List[QPointF], fraction: float) -> QPointF:
        """
        Return point at 'fraction' of total polyline length (0..1),
        using Euclidean length of drawn geometry.
        """
        fraction = max(0.0, min(1.0, fraction))
        seglens = []
        total = 0.0
        for a, b in zip(pts[:-1], pts[1:]):
            dx = b.x() - a.x()
            dy = b.y() - a.y()
            l = math.hypot(dx, dy)
            seglens.append(l)
            total += l

        if total <= 1e-9:
            return pts[0]

        target = fraction * total
        acc = 0.0
        for (a, b, l) in zip(pts[:-1], pts[1:], seglens):
            if acc + l >= target:
                t = (target - acc) / l if l > 1e-9 else 0.0
                return QPointF(a.x() + t * (b.x() - a.x()), a.y() + t * (b.y() - a.y()))
            acc += l
        return pts[-1]

    def _timing_point_position(self, tp: TimingPoint) -> Optional[QPointF]:
        tr = self._tracks.get(tp.track_id)
        if tr is None or tr.length_m <= 0:
            return None
        pts = self._polyline_points_for_track(tr)
        if pts is None:
            return None

        # distanceToTargetNodeInMeters is measured towards tp.target_node_id
        if tp.target_node_id == tr.target:
            frac = (tr.length_m - tp.distance_to_target_m) / tr.length_m
        elif tp.target_node_id == tr.source:
            frac = tp.distance_to_target_m / tr.length_m
        else:
            # unexpected; fallback to center
            frac = 0.5
        return self._point_along_polyline(pts, frac)

    def _stopping_location_position(self, sl: StoppingLocation) -> Optional[QPointF]:
        tr = self._tracks.get(sl.track_id)
        if tr is None or tr.length_m <= 0:
            return None
        pts = self._polyline_points_for_track(tr)
        if pts is None:
            return None

        if sl.reference_node_id == tr.source:
            frac = sl.distance_from_ref_m / tr.length_m
        elif sl.reference_node_id == tr.target:
            frac = (tr.length_m - sl.distance_from_ref_m) / tr.length_m
        else:
            frac = 0.5
        return self._point_along_polyline(pts, frac)

    def _compute_node_positions(self) -> Dict[str, QPointF]:
        if self._layout_mode == "topological":
            return self._compute_topological_positions()
        self._topo_node_index = {}
        self._topo_station_layout = []
        self._node_to_station = {}
        self._station_rep_node_id = {}
        self._station_rect_items = {}
        return {node.id: QPointF(node.x, node.y) for node in self._nodes.values()}

    def _station_nodes_map(self) -> Dict[str, set[str]]:
        """
        Map station/group name -> set(nodeIds) based on stoppingLocationGroups.

        This is a heuristic: we use the stopping location's reference/target-direction nodes
        and the endpoints of the track the stopping location sits on.
        """
        group_to_nodes: Dict[str, set[str]] = {}
        for sl_id, group in self._sl_to_group.items():
            if not group:
                continue
            sl = self._stopping_locations.get(sl_id)
            if sl is None:
                continue

            nodes = group_to_nodes.setdefault(group, set())
            if sl.reference_node_id in self._nodes:
                nodes.add(sl.reference_node_id)
            if sl.target_direction_node_id in self._nodes:
                nodes.add(sl.target_direction_node_id)

            tr = self._tracks.get(sl.track_id)
            if tr is not None:
                if tr.source in self._nodes:
                    nodes.add(tr.source)
                if tr.target in self._nodes:
                    nodes.add(tr.target)

        return {name: nodes for (name, nodes) in group_to_nodes.items() if nodes}

    # -----------------
    # Schematic helpers
    # -----------------

    def _build_schematic_graph(self) -> None:
        """
        Build a simplified multigraph for schematic rendering.

        - Nodes with exactly 2 unique neighbors are contracted away (unless part of a station group).
        - Each resulting schematic segment represents a chain of original node-to-node hops.
        - Parallel tracks on the same hop are bundled into the same segment (track_ids list).
        """
        self._schem_keep_nodes = set()
        self._schem_segments = {}
        self._schem_adj = {}
        self._schem_track_to_segment = {}
        self._schem_segment_parallel_offset_y = {}
        self._schem_tree_segment_ids = set()

        # Station mapping (for labels / route selection)
        self._node_to_station = {}
        self._station_rep_node_id = {}
        station_nodes = self._station_nodes_map()
        station_node_set: set[str] = set()
        for name, nodes in station_nodes.items():
            station_node_set |= nodes
            ordered = sorted(nodes, key=self._node_sort_key)
            if ordered:
                rep = ordered[len(ordered) // 2]
                self._station_rep_node_id[name] = rep
            for nid in nodes:
                self._node_to_station.setdefault(nid, name)

        # Hop bundling between original node pairs
        pair_to_track_ids: Dict[Tuple[str, str], List[str]] = {}
        for tr in self._tracks.values():
            if tr.source not in self._nodes or tr.target not in self._nodes:
                continue
            a, b = (tr.source, tr.target)
            if a > b:
                a, b = b, a
            pair_to_track_ids.setdefault((a, b), []).append(tr.id)

        neighbors: Dict[str, set[str]] = {nid: set() for nid in self._nodes.keys()}
        for (a, b) in pair_to_track_ids.keys():
            neighbors.setdefault(a, set()).add(b)
            neighbors.setdefault(b, set()).add(a)

        # Contract degree-2 nodes (in the simple unique-neighbor sense), except station nodes.
        contractible: set[str] = set()
        for nid, nbs in neighbors.items():
            if nid in station_node_set:
                continue
            if len(nbs) == 2:
                contractible.add(nid)

        self._schem_keep_nodes = set(self._nodes.keys()) - contractible

        visited_hops: set[Tuple[str, str]] = set()
        seg_idx = 0

        def hop_min_length(a: str, b: str) -> float:
            x, y = (a, b) if a < b else (b, a)
            tids = pair_to_track_ids.get((x, y), [])
            best = math.inf
            for tid in tids:
                tr = self._tracks.get(tid)
                if tr is None:
                    continue
                best = min(best, tr.length_m if tr.length_m > 0 else 1.0)
            return best if best != math.inf else 1.0

        for u in sorted(self._schem_keep_nodes, key=self._node_sort_key):
            for v in sorted(neighbors.get(u, set()), key=self._node_sort_key):
                a, b = (u, v) if u < v else (v, u)
                if (a, b) in visited_hops:
                    continue

                node_path: List[str] = [u]
                track_ids: List[str] = []
                length_m = 0.0
                hops: List[Tuple[str, str]] = []

                prev = u
                cur = v
                while True:
                    node_path.append(cur)
                    ha, hb = (prev, cur) if prev < cur else (cur, prev)
                    hops.append((ha, hb))
                    tids = pair_to_track_ids.get((ha, hb), [])
                    track_ids.extend(tids)
                    length_m += hop_min_length(prev, cur)

                    if cur in self._schem_keep_nodes:
                        break

                    nbs = list(neighbors.get(cur, set()))
                    if len(nbs) != 2:
                        # Fallback: treat this as a keep node for the traversal.
                        self._schem_keep_nodes.add(cur)
                        break

                    if nbs[0] == prev:
                        nxt = nbs[1]
                    elif nbs[1] == prev:
                        nxt = nbs[0]
                    else:
                        break

                    prev, cur = cur, nxt

                    # Stop on small loops; the remaining hops will be handled by other traversals.
                    ha2, hb2 = (prev, cur) if prev < cur else (cur, prev)
                    if (ha2, hb2) in visited_hops:
                        break

                for hop in hops:
                    visited_hops.add(hop)

                if len(node_path) < 2:
                    continue

                seg_id = f"__schem_seg__:{seg_idx}"
                seg_idx += 1
                unique_tracks = sorted({tid for tid in track_ids if tid in self._tracks})
                seg = SchematicSegment(
                    id=seg_id,
                    source=node_path[0],
                    target=node_path[-1],
                    node_path=node_path,
                    track_ids=unique_tracks,
                    length_m=length_m if length_m > 0 else 1.0,
                )
                self._schem_segments[seg_id] = seg

        # Build adjacency and track->segment mapping
        self._schem_adj = {nid: [] for nid in self._schem_keep_nodes}
        for seg in self._schem_segments.values():
            if seg.source not in self._schem_adj or seg.target not in self._schem_adj:
                continue
            w = seg.length_m if seg.length_m > 0 else 1.0
            self._schem_adj[seg.source].append((seg.target, seg.id, w))
            self._schem_adj[seg.target].append((seg.source, seg.id, w))
            for tid in seg.track_ids:
                self._schem_track_to_segment.setdefault(tid, seg.id)

        # Small offsets for parallel segments between the same endpoints.
        by_pair: Dict[Tuple[str, str], List[str]] = {}
        for seg in self._schem_segments.values():
            a, b = (seg.source, seg.target) if seg.source < seg.target else (seg.target, seg.source)
            by_pair.setdefault((a, b), []).append(seg.id)

        for (a, b), seg_ids in by_pair.items():
            if len(seg_ids) <= 1:
                continue
            seg_ids = sorted(seg_ids)
            mid = (len(seg_ids) - 1) / 2.0
            for i, sid in enumerate(seg_ids):
                self._schem_segment_parallel_offset_y[sid] = (i - mid) * 10.0

    def _schem_connected_components(self, nodes: set[str]) -> List[List[str]]:
        remaining = set(nodes)
        components: List[List[str]] = []
        while remaining:
            start = min(remaining, key=self._node_sort_key)
            stack = [start]
            remaining.remove(start)
            comp: List[str] = []
            while stack:
                u = stack.pop()
                comp.append(u)
                for v, _, _ in self._schem_adj.get(u, []):
                    if v in remaining:
                        remaining.remove(v)
                        stack.append(v)
            components.append(comp)
        return components

    def _schem_dijkstra(
        self,
        start_nodes: List[str],
        allowed: set[str],
    ) -> Tuple[Dict[str, float], Dict[str, str], Dict[str, str], Dict[str, str]]:
        """
        Multi-source Dijkstra on the schematic graph.

        Returns (dist, prev_node, prev_edge, root_backbone).
        """
        import heapq

        dist: Dict[str, float] = {}
        prev_node: Dict[str, str] = {}
        prev_edge: Dict[str, str] = {}
        root: Dict[str, str] = {}
        pq: List[Tuple[float, str]] = []

        for s in start_nodes:
            if s not in allowed:
                continue
            dist[s] = 0.0
            root[s] = s
            heapq.heappush(pq, (0.0, s))

        while pq:
            d, u = heapq.heappop(pq)
            if d != dist.get(u, float("inf")):
                continue
            for v, seg_id, w in self._schem_adj.get(u, []):
                if v not in allowed:
                    continue
                nd = d + (w if w > 0 else 1.0)
                if nd < dist.get(v, float("inf")):
                    dist[v] = nd
                    prev_node[v] = u
                    prev_edge[v] = seg_id
                    root[v] = root.get(u, u)
                    heapq.heappush(pq, (nd, v))

        return dist, prev_node, prev_edge, root

    def _compute_schematic_positions(self) -> Dict[str, QPointF]:
        """
        Backbone + branches layout on the contracted schematic graph.

        - Pick a backbone path (approx. diameter) and place it on y=0.
        - Attach the remaining nodes as trees above/below the backbone using a tidy-tree layout.
        """
        positions: Dict[str, QPointF] = {}
        self._schem_tree_segment_ids = set()

        if not self._schem_keep_nodes:
            return positions

        components = self._schem_connected_components(self._schem_keep_nodes)

        x_offset = 0.0
        component_gap = 520.0
        backbone_node_spacing = 220.0

        for comp in components:
            comp_set = set(comp)

            # Prefer a station representative as anchor when available.
            anchors = [nid for nid in self._station_rep_node_id.values() if nid in comp_set]
            start = anchors[0] if anchors else min(comp_set, key=self._node_sort_key)

            dist1, _, _, _ = self._schem_dijkstra([start], comp_set)
            if not dist1:
                # Isolated node
                positions[start] = QPointF(x_offset, 0.0)
                x_offset += component_gap
                continue

            a = max(dist1.items(), key=lambda kv: kv[1])[0]
            dist2, prev2, prev_edge2, _ = self._schem_dijkstra([a], comp_set)
            b = max(dist2.items(), key=lambda kv: kv[1])[0]

            backbone_nodes: List[str] = [b]
            backbone_edges: List[str] = []
            cur = b
            while cur != a and cur in prev2:
                backbone_edges.append(prev_edge2[cur])
                cur = prev2[cur]
                backbone_nodes.append(cur)
            backbone_nodes.reverse()
            backbone_edges.reverse()

            backbone_set = set(backbone_nodes)

            # Place backbone on the baseline (y=0) from left to right.
            x = x_offset
            positions[backbone_nodes[0]] = QPointF(x, 0.0)
            for u, seg_id in zip(backbone_nodes[1:], backbone_edges):
                seg = self._schem_segments.get(seg_id)
                w = seg.length_m if seg is not None else 1.0
                dx = backbone_node_spacing + min(320.0, math.log1p(max(0.0, w)) * 35.0)
                x += dx
                positions[u] = QPointF(x, 0.0)

            # Multi-source shortest-path forest rooted at the backbone nodes.
            dist_f, prev_f, prev_edge_f, root = self._schem_dijkstra(backbone_nodes, comp_set)
            children: Dict[str, List[str]] = {nid: [] for nid in comp_set}
            for nid, parent in prev_f.items():
                if nid in backbone_set:
                    continue
                children.setdefault(parent, []).append(nid)

            tree_segment_ids = set(backbone_edges)
            tree_segment_ids |= {eid for nid, eid in prev_edge_f.items() if nid not in backbone_set}
            self._schem_tree_segment_ids |= tree_segment_ids

            leaf_gap = 34.0
            band_padding = 30.0
            attach_dx = 140.0
            depth_dx = 110.0
            first_branch_offset = 170.0

            def leaf_count(nid: str) -> int:
                kids = children.get(nid, [])
                if not kids:
                    return 1
                return sum(leaf_count(k) for k in kids)

            def layout_subtree(
                nid: str,
                *,
                depth: int,
                x0: float,
                origin: float,
                sign: float,
                cursor: List[float],
            ) -> float:
                kids = sorted(children.get(nid, []), key=self._node_sort_key)
                x_here = x0 + depth * depth_dx
                if not kids:
                    y_local = cursor[0]
                    cursor[0] += leaf_gap
                    positions[nid] = QPointF(x_here, sign * (origin + y_local))
                    return y_local

                child_centers: List[float] = []
                for k in kids:
                    child_centers.append(
                        layout_subtree(k, depth=depth + 1, x0=x0, origin=origin, sign=sign, cursor=cursor)
                    )
                y_local = (child_centers[0] + child_centers[-1]) / 2.0
                positions[nid] = QPointF(x_here, sign * (origin + y_local))
                return y_local

            # Attach branches per backbone node in separate vertical bands above and below.
            for bnode in backbone_nodes:
                bx = positions[bnode].x()
                branch_roots = [c for c in children.get(bnode, []) if c not in backbone_set]
                if not branch_roots:
                    continue

                branch_roots = sorted(branch_roots, key=self._node_sort_key)
                up_offset = first_branch_offset
                down_offset = first_branch_offset

                for i, rnode in enumerate(branch_roots):
                    leaves = leaf_count(rnode)
                    height = leaves * leaf_gap
                    if i % 2 == 0:
                        sign = -1.0
                        origin = up_offset
                        up_offset += height + band_padding
                    else:
                        sign = 1.0
                        origin = down_offset
                        down_offset += height + band_padding

                    cursor = [0.0]
                    layout_subtree(
                        rnode,
                        depth=0,
                        x0=bx + attach_dx,
                        origin=origin,
                        sign=sign,
                        cursor=cursor,
                    )

            # Any leftover nodes (rare): place near their closest backbone root.
            for nid in comp_set:
                if nid in positions:
                    continue
                rb = root.get(nid)
                if rb and rb in positions:
                    positions[nid] = QPointF(positions[rb].x() + attach_dx, first_branch_offset)
                else:
                    positions[nid] = QPointF(x_offset, 0.0)

            x_offset = max(x_offset, x) + component_gap

        return positions

    def _schematic_segment_path(self, seg: SchematicSegment) -> Optional[QPainterPath]:
        a = self._node_positions.get(seg.source)
        b = self._node_positions.get(seg.target)
        if a is None or b is None:
            return None

        # Slight offset for parallel segments
        off = float(self._schem_segment_parallel_offset_y.get(seg.id, 0.0))

        p0 = QPointF(a)
        p1 = QPointF(b)
        mid_x = (p0.x() + p1.x()) / 2.0
        mid_x += off

        base = [p0, QPointF(mid_x, p0.y()), QPointF(mid_x, p1.y()), p1]
        dy = abs(float(p1.y() - p0.y()))
        bevel = min(32.0, 0.35 * dy)
        pts = self._axis_polyline_with_45deg_corners(base, bevel=bevel)
        return self._path_from_points(pts)

    def _plan_segment_path(
        self,
        p0: QPointF,
        p1: QPointF,
        *,
        n_tracks: int,
        track_spacing: float,
    ) -> QPainterPath:
        """
        Orthogonal connection with 45° chamfers, optionally repeated for N parallel tracks.

        Note: this operates purely on endpoints (plan has "station ports"), not on node IDs.
        """
        p0 = QPointF(p0)
        p1 = QPointF(p1)

        dx = float(p1.x() - p0.x())
        dy = float(p1.y() - p0.y())

        if abs(dy) <= 1e-6:
            base = [p0, p1]
        else:
            sign = 1.0 if dx >= 0.0 else -1.0
            abs_dx = abs(dx)
            stub = min(150.0, max(70.0, abs_dx * 0.18))
            stub = min(stub, abs_dx / 2.0) if abs_dx > 1e-6 else 0.0
            x0 = p0.x() + sign * stub
            x1 = p1.x() - sign * stub
            if abs_dx <= 1e-6:
                x0 = p0.x()
                x1 = p1.x()
            if (sign > 0 and x0 > x1) or (sign < 0 and x0 < x1):
                x0 = (p0.x() + p1.x()) / 2.0
                x1 = x0
            base = [p0, QPointF(x0, p0.y()), QPointF(x1, p0.y()), QPointF(x1, p1.y()), p1]

        bevel = min(36.0, 0.35 * max(18.0, abs(dy)))
        pts = self._axis_polyline_with_45deg_corners(base, bevel=bevel)

        n_tracks = max(1, min(6, int(n_tracks)))
        if n_tracks == 1:
            return self._path_from_points(pts)

        mid = (n_tracks - 1) / 2.0
        path = QPainterPath()
        for i in range(n_tracks):
            offset = (i - mid) * float(track_spacing)
            o_pts = self._offset_polyline(pts, offset)
            if len(o_pts) >= 2:
                path.addPath(self._path_from_points(o_pts))
        return path

    def _compute_plan_positions(self) -> Dict[str, QPointF]:
        """
        Layout for plan view (more spacing and a stronger "mainline" compared to schematic).
        """
        positions: Dict[str, QPointF] = {}
        self._schem_tree_segment_ids = set()

        if not self._schem_keep_nodes:
            return positions

        components = self._schem_connected_components(self._schem_keep_nodes)

        x_offset = 0.0
        component_gap = 620.0
        backbone_node_spacing = 240.0

        for comp in components:
            comp_set = set(comp)

            anchors = [nid for nid in self._station_rep_node_id.values() if nid in comp_set]
            start = anchors[0] if anchors else min(comp_set, key=self._node_sort_key)

            dist1, _, _, _ = self._schem_dijkstra([start], comp_set)
            if not dist1:
                positions[start] = QPointF(x_offset, 0.0)
                x_offset += component_gap
                continue

            a = max(dist1.items(), key=lambda kv: kv[1])[0]
            dist2, prev2, prev_edge2, _ = self._schem_dijkstra([a], comp_set)
            b = max(dist2.items(), key=lambda kv: kv[1])[0]

            backbone_nodes: List[str] = [b]
            backbone_edges: List[str] = []
            cur = b
            while cur != a and cur in prev2:
                backbone_edges.append(prev_edge2[cur])
                cur = prev2[cur]
                backbone_nodes.append(cur)
            backbone_nodes.reverse()
            backbone_edges.reverse()
            backbone_set = set(backbone_nodes)

            x = x_offset
            positions[backbone_nodes[0]] = QPointF(x, 0.0)
            for u, seg_id in zip(backbone_nodes[1:], backbone_edges):
                seg = self._schem_segments.get(seg_id)
                w = seg.length_m if seg is not None else 1.0
                dx = backbone_node_spacing + min(520.0, math.log1p(max(0.0, w)) * 55.0)
                x += dx
                positions[u] = QPointF(x, 0.0)

            dist_f, prev_f, prev_edge_f, root = self._schem_dijkstra(backbone_nodes, comp_set)
            children: Dict[str, List[str]] = {nid: [] for nid in comp_set}
            for nid, parent in prev_f.items():
                if nid in backbone_set:
                    continue
                children.setdefault(parent, []).append(nid)

            tree_segment_ids = set(backbone_edges)
            tree_segment_ids |= {eid for nid, eid in prev_edge_f.items() if nid not in backbone_set}
            self._schem_tree_segment_ids |= tree_segment_ids

            leaf_gap = 40.0
            band_padding = 55.0
            attach_dx = 180.0
            depth_dx = 140.0
            first_branch_offset = 220.0

            def leaf_count(nid: str) -> int:
                kids = children.get(nid, [])
                if not kids:
                    return 1
                return sum(leaf_count(k) for k in kids)

            def layout_subtree(
                nid: str,
                *,
                depth: int,
                x0: float,
                origin: float,
                sign: float,
                cursor: List[float],
            ) -> float:
                kids = sorted(children.get(nid, []), key=self._node_sort_key)
                x_here = x0 + depth * depth_dx
                if not kids:
                    y_local = cursor[0]
                    cursor[0] += leaf_gap
                    positions[nid] = QPointF(x_here, sign * (origin + y_local))
                    return y_local

                child_centers: List[float] = []
                for k in kids:
                    child_centers.append(
                        layout_subtree(k, depth=depth + 1, x0=x0, origin=origin, sign=sign, cursor=cursor)
                    )
                y_local = (child_centers[0] + child_centers[-1]) / 2.0
                positions[nid] = QPointF(x_here, sign * (origin + y_local))
                return y_local

            up_offset = 0.0
            down_offset = 0.0
            for bnode in backbone_nodes:
                bx = positions[bnode].x()
                branch_roots = [c for c in children.get(bnode, []) if c not in backbone_set]
                if not branch_roots:
                    continue

                branch_roots = sorted(branch_roots, key=lambda n: (-leaf_count(n), self._node_sort_key(n)))
                flip = True
                for rnode in branch_roots:
                    height = max(1, leaf_count(rnode)) * leaf_gap
                    if flip:
                        origin = first_branch_offset + up_offset
                        sign = -1.0
                        up_offset += height + band_padding
                    else:
                        origin = first_branch_offset + down_offset
                        sign = 1.0
                        down_offset += height + band_padding
                    flip = not flip

                    cursor = [0.0]
                    layout_subtree(
                        rnode,
                        depth=0,
                        x0=bx + attach_dx,
                        origin=origin,
                        sign=sign,
                        cursor=cursor,
                    )

            for nid in comp_set:
                if nid in positions:
                    continue
                rb = root.get(nid)
                if rb and rb in positions:
                    positions[nid] = QPointF(positions[rb].x() + attach_dx, first_branch_offset)
                else:
                    positions[nid] = QPointF(x_offset, 0.0)

            x_offset = max(x_offset, x) + component_gap

        # Small quantization for the plan look.
        qy = 6.0
        for nid, p in list(positions.items()):
            positions[nid] = QPointF(p.x(), round(p.y() / qy) * qy)

        return positions

    def _plan_build_station_blocks(
        self,
        *,
        pair_parallel: Dict[Tuple[str, str], int],
        segment_parallel_tracks,
        track_spacing: float,
        block_len: float,
    ) -> Tuple[Dict[Tuple[str, str], QPointF], Dict[str, Tuple[str, QPointF, int]]]:
        """
        Returns:
        - endpoint position overrides: (segmentId, endpointNodeId) -> QPointF
        - station blocks: stationName -> (repNodeId, centerPos, trackCount)
        """
        endpoint_overrides: Dict[Tuple[str, str], QPointF] = {}
        station_blocks: Dict[str, Tuple[str, QPointF, int]] = {}

        if not self._station_rep_node_id:
            return endpoint_overrides, station_blocks

        # Determine station track counts from external connections (heuristic).
        station_node_sets = self._station_nodes_map()
        schem_station_nodes: Dict[str, set[str]] = {}
        for name, rep in self._station_rep_node_id.items():
            nodes = {nid for nid, s in self._node_to_station.items() if s == name and nid in self._schem_keep_nodes}
            if not nodes:
                # fallback to heuristic station nodes (intersect keep set)
                nodes = {nid for nid in station_node_sets.get(name, set()) if nid in self._schem_keep_nodes}
            schem_station_nodes[name] = nodes

        def estimated_station_tracks(name: str) -> int:
            nodes = schem_station_nodes.get(name, set())
            if not nodes:
                return 1
            external = 0
            for seg in self._schem_segments.values():
                a_in = seg.source in nodes
                b_in = seg.target in nodes
                if a_in == b_in:
                    continue
                external += int(segment_parallel_tracks(seg))
            return max(1, int(math.ceil(external / 2.0)))

        for name, rep_node_id in sorted(self._station_rep_node_id.items(), key=lambda kv: kv[0]):
            pos = self._node_positions.get(rep_node_id)
            if pos is None:
                continue
            n_tracks = max(1, min(10, estimated_station_tracks(name)))
            station_blocks[name] = (rep_node_id, QPointF(pos), n_tracks)

        # Assign station "ports" per connected segment so lines attach to visible station tracks.
        block_len = float(block_len)
        spacing = float(track_spacing)

        for name, (rep_node_id, center, n_tracks) in station_blocks.items():
            nodes = schem_station_nodes.get(name, set())
            if not nodes:
                continue

            lanes = [center.y() + (i - (n_tracks - 1) / 2.0) * spacing for i in range(n_tracks)]
            lane_indices = list(range(n_tracks))

            left: List[Tuple[float, str, str]] = []   # (other_y, segId, endpointNodeId)
            right: List[Tuple[float, str, str]] = []
            for seg in self._schem_segments.values():
                if seg.source in nodes and seg.target not in nodes:
                    other = self._node_positions.get(seg.target)
                    if other is None:
                        continue
                    side = left if other.x() < center.x() else right
                    side.append((float(other.y()), seg.id, seg.source))
                elif seg.target in nodes and seg.source not in nodes:
                    other = self._node_positions.get(seg.source)
                    if other is None:
                        continue
                    side = left if other.x() < center.x() else right
                    side.append((float(other.y()), seg.id, seg.target))

            def assign_ports(items: List[Tuple[float, str, str]], *, x: float) -> None:
                if not items:
                    return
                items.sort(key=lambda t: (t[0], t[1], t[2]))
                if len(items) <= n_tracks:
                    # Spread across lanes in order.
                    for (item, li) in zip(items, lane_indices):
                        _, seg_id, endpoint = item
                        endpoint_overrides[(seg_id, endpoint)] = QPointF(x, lanes[li])
                else:
                    # More connections than tracks: wrap but keep visual order.
                    for idx, item in enumerate(items):
                        _, seg_id, endpoint = item
                        li = lane_indices[idx % n_tracks]
                        endpoint_overrides[(seg_id, endpoint)] = QPointF(x, lanes[li])

            assign_ports(left, x=center.x() - block_len / 2.0)
            assign_ports(right, x=center.x() + block_len / 2.0)

        return endpoint_overrides, station_blocks

    def _plan_draw_station_blocks(
        self,
        station_blocks: Dict[str, Tuple[str, QPointF, int]],
        *,
        track_spacing: float,
        block_len: float,
    ) -> None:
        if not station_blocks:
            return

        if self._current_theme == "dark":
            outer_pen = QPen(Qt.GlobalColor.lightGray)
        else:
            outer_pen = QPen(Qt.GlobalColor.black)
        outer_pen.setWidthF(7.2)
        outer_pen.setCapStyle(Qt.PenCapStyle.RoundCap)
        outer_pen.setJoinStyle(Qt.PenJoinStyle.RoundJoin)

        for name, (rep_node_id, center, n_tracks) in station_blocks.items():
            n_tracks = max(1, int(n_tracks))
            mid = (n_tracks - 1) / 2.0
            x0 = center.x() - block_len / 2.0
            x1 = center.x() + block_len / 2.0

            path = QPainterPath()
            for i in range(n_tracks):
                y = center.y() + (i - mid) * float(track_spacing)
                path.moveTo(QPointF(x0, y))
                path.lineTo(QPointF(x1, y))

            outer = QGraphicsPathItem(path)
            outer.setPen(outer_pen)
            outer.setZValue(2.0)
            outer.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            outer.setData(1, rep_node_id)
            outer.setData(2, "station")
            outer.setToolTip(f"{name}\nGleise≈{n_tracks}")
            self._scene.addItem(outer)

            # Track numbers (1..N)
            for i in range(n_tracks):
                y = center.y() + (i - mid) * float(track_spacing)
                num = QGraphicsSimpleTextItem(str(i + 1))
                if self._current_theme == "dark":
                    num.setBrush(QBrush(Qt.GlobalColor.white))
                else:
                    num.setBrush(QBrush(Qt.GlobalColor.black))
                num.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
                num.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
                brn = num.boundingRect()
                num.setPos(QPointF(x1 + 8.0, y - brn.height() / 2.0))
                num.setZValue(25.0)
                num.setData(1, rep_node_id)
                num.setData(2, "station")
                self._scene.addItem(num)

            # Label with white box (click target for route selection).
            label_text = name if len(name) <= 34 else (name[:31].rstrip() + "...")
            label = QGraphicsSimpleTextItem(label_text)
            if self._current_theme == "dark":
                label.setBrush(QBrush(Qt.GlobalColor.white))
            else:
                label.setBrush(QBrush(Qt.GlobalColor.black))
            label.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            label.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
            label.setData(1, rep_node_id)
            label.setData(2, "station")
            br = label.boundingRect()
            if center.y() >= 0.0:
                label_y = center.y() + (20.0 + mid * track_spacing)
            else:
                label_y = center.y() - (46.0 + mid * track_spacing)
            label_pos = QPointF(center.x() - br.width() / 2.0, label_y)

            box = QGraphicsRectItem(QRectF(0.0, 0.0, br.width() + 12.0, br.height() + 8.0))
            box.setPos(QPointF(label_pos.x() - 6.0, label_pos.y() - 4.0))
            if self._current_theme == "dark":
                box.setBrush(QBrush(QColor(34, 34, 34)))
                box_pen = QPen(Qt.GlobalColor.white)
            else:
                box.setBrush(QBrush(Qt.GlobalColor.white))
                box_pen = QPen(Qt.GlobalColor.black)
            box_pen.setWidthF(1.0)
            box.setPen(box_pen)
            box.setZValue(20.0)
            box.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
            box.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            box.setData(1, rep_node_id)
            box.setData(2, "station")
            box.setToolTip(f"{name}\nGleise≈{n_tracks}")
            self._scene.addItem(box)

            label.setPos(label_pos)
            label.setZValue(21.0)
            self._scene.addItem(label)

    def _add_schematic_station_markers(self) -> None:
        # Clear old station overlay items
        for it in getattr(self, "_schem_station_items", []):
            try:
                self._scene.removeItem(it)
            except Exception:
                pass
        self._schem_station_items = []

        if not self._station_rep_node_id:
            return

        station_nodes = self._station_nodes_map()

        def estimated_station_tracks(nodes: set[str]) -> int:
            external = 0
            for seg in self._schem_segments.values():
                a_in = seg.source in nodes
                b_in = seg.target in nodes
                if a_in == b_in:
                    continue
                external += max(1, len(seg.track_ids))
            # Each through track typically contributes two external connections (left/right).
            return max(1, int(math.ceil(external / 2.0)))

        for name, rep_node_id in sorted(self._station_rep_node_id.items(), key=lambda kv: kv[0]):
            pos = self._node_positions.get(rep_node_id)
            if pos is None:
                continue

            nodes = station_nodes.get(name, set())
            n_tracks = estimated_station_tracks(nodes) if nodes else 1
            dot = QGraphicsEllipseItem(-7.0, -7.0, 14.0, 14.0)
            dot.setPos(pos)
            dot.setBrush(QBrush(Qt.GlobalColor.red))
            
            if self._current_theme == "dark":
                dot_pen = QPen(QColor(34, 34, 34))
            else:
                dot_pen = QPen(Qt.GlobalColor.black)
            dot_pen.setWidthF(1.0)
            dot.setPen(dot_pen)
            dot.setZValue(30)
            dot.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
            dot.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            dot.setData(1, rep_node_id)
            dot.setData(2, "station")
            dot.setToolTip(f"{name}\nGleise≈{n_tracks}")
            self._scene.addItem(dot)
            self._schem_station_items.append(dot)

            label_text = name
            if len(label_text) > 28:
                label_text = label_text[:25].rstrip() + "..."
            label = QGraphicsSimpleTextItem(label_text)
            label.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            label.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
            
            if self._current_theme == "dark":
                label.setBrush(QBrush(Qt.GlobalColor.white))
            else:
                label.setBrush(QBrush(Qt.GlobalColor.black))

            label.setData(1, rep_node_id)
            label.setData(2, "station")
            br = label.boundingRect()
            label.setPos(QPointF(pos.x() - br.width() / 2.0, pos.y() - 22.0))
            label.setZValue(31)
            self._scene.addItem(label)
            self._schem_station_items.append(label)

    @staticmethod

    def _median(values: List[float]) -> float:
        if not values:
            return math.inf
        values = sorted(values)
        return values[len(values) // 2]

    def _compute_topological_positions(self) -> Dict[str, QPointF]:
        positions: Dict[str, QPointF] = {}
        if not self._nodes:
            return positions

        # Schematic layout:
        # - cluster nodes by station/stoppingLocationGroup
        # - keep everything mostly 1D (y=0) for route planning
        # - add large gaps between stations so the view is readable when zoomed out
        self._topo_node_index = {}
        self._topo_station_layout = []
        self._node_to_station = {}
        self._station_rep_node_id = {}
        self._station_rect_items = {}

        node_spacing = 190.0
        group_node_spacing = 115.0
        group_padding = 160.0
        group_gap = 520.0
        component_gap = 640.0

        station_nodes = self._station_nodes_map()

        def station_key(nodes: set[str]) -> float:
            nums = [
                float(self._nodes[nid].numeric_id)
                for nid in nodes
                if nid in self._nodes and self._nodes[nid].numeric_id is not None
            ]
            return self._median(nums)

        current_x_offset = 0.0
        global_idx = 0
        for comp_idx, comp in enumerate(self._connected_components()):
            comp_set = set(comp)

            comp_station_nodes: Dict[str, set[str]] = {}
            for name, nodes in station_nodes.items():
                inter = nodes & comp_set
                if inter:
                    comp_station_nodes[name] = inter

            grouped_nodes: set[str] = set()
            for nodes in comp_station_nodes.values():
                grouped_nodes |= nodes

            ungrouped = [nid for nid in comp if nid not in grouped_nodes]

            elements: List[Tuple[float, int, str]] = []
            group_payload: Dict[str, List[str]] = {}

            for name, nodes in comp_station_nodes.items():
                group_payload[name] = sorted(nodes, key=self._node_sort_key)
                rep = group_payload[name][len(group_payload[name]) // 2]
                self._station_rep_node_id[name] = rep
                for nid in group_payload[name]:
                    self._node_to_station.setdefault(nid, name)
                elements.append((station_key(nodes), 0, name))

            for nid in ungrouped:
                node = self._nodes.get(nid)
                key = float(node.numeric_id) if node and node.numeric_id is not None else math.inf
                elements.append((key, 1, nid))

            # kind: 0 = station cluster, 1 = standalone node
            elements.sort(key=lambda t: (t[0], t[1], t[2]))

            for _, kind, payload in elements:
                if kind == 0:
                    name = payload
                    nodes = group_payload.get(name, [])
                    if not nodes:
                        continue

                    x0 = current_x_offset
                    x = current_x_offset + group_padding
                    for nid in nodes:
                        positions[nid] = QPointF(x, 0.0)
                        self._topo_node_index[nid] = global_idx
                        global_idx += 1
                        x += group_node_spacing
                    x1 = (x - group_node_spacing) + group_padding

                    self._topo_station_layout.append((name, x0, x1, comp_idx))
                    current_x_offset = x1 + group_gap
                else:
                    nid = payload
                    positions[nid] = QPointF(current_x_offset, 0.0)
                    self._topo_node_index[nid] = global_idx
                    global_idx += 1
                    current_x_offset += node_spacing

            current_x_offset += component_gap

        return positions

    def _connected_components(self) -> List[List[str]]:
        remaining = set(self._nodes.keys())
        components: List[List[str]] = []
        while remaining:
            start = min(remaining, key=self._node_sort_key)
            stack = [start]
            remaining.remove(start)
            comp: List[str] = []
            while stack:
                u = stack.pop()
                comp.append(u)
                for v, _, _ in self._graph.get(u, []):
                    if v in remaining:
                        remaining.remove(v)
                        stack.append(v)
            components.append(comp)
        return components

    @staticmethod

    def _intervals_overlap(a0: int, a1: int, b0: int, b1: int) -> bool:
        return not (a1 <= b0 or b1 <= a0)

    def _compute_topological_track_offsets(self) -> Dict[str, float]:
        """
        Assign per-track vertical offsets for schematic (topological) rendering.

        - "Mainline" tracks between adjacent nodes are drawn on the baseline (y=0).
        - Additional parallel tracks between adjacent nodes get small offsets.
        - Longer connections are routed as arcs in higher lanes to stay readable.
        """
        idx = self._topo_node_index
        if not idx:
            return {}

        adjacent: Dict[Tuple[int, int], List[str]] = {}
        skip_intervals: List[Tuple[int, int, str]] = []

        for tr in self._tracks.values():
            a = idx.get(tr.source)
            b = idx.get(tr.target)
            if a is None or b is None or a == b:
                continue
            i0, i1 = (a, b) if a < b else (b, a)
            if i1 - i0 == 1:
                adjacent.setdefault((i0, i1), []).append(tr.id)
            else:
                skip_intervals.append((i0, i1, tr.id))

        offsets: Dict[str, float] = {}

        parallel_gap = 14.0
        for _, track_ids in adjacent.items():
            # Pick one to represent the baseline connection.
            baseline = min(
                track_ids,
                key=lambda tid: (
                    self._tracks[tid].length_m if self._tracks[tid].length_m > 0 else math.inf,
                    tid,
                ),
            )
            offsets[baseline] = 0.0
            others = [tid for tid in track_ids if tid != baseline]
            for k, tid in enumerate(sorted(others)):
                offsets[tid] = (k + 1) * parallel_gap

        lane_spacing = 72.0
        lanes: List[List[Tuple[int, int]]] = []
        skip_intervals.sort(key=lambda t: (-(t[1] - t[0]), t[0], t[2]))

        for a0, a1, tid in skip_intervals:
            if tid in offsets:
                continue
            lane_idx: Optional[int] = None
            for i, lane in enumerate(lanes):
                if all(not self._intervals_overlap(a0, a1, b0, b1) for (b0, b1) in lane):
                    lane_idx = i
                    lane.append((a0, a1))
                    break
            if lane_idx is None:
                lane_idx = len(lanes)
                lanes.append([(a0, a1)])
            offsets[tid] = (lane_idx + 1) * lane_spacing

        return offsets

    def _add_topological_station_markers(self) -> None:
        self._station_rect_items = {}
        if not self._topo_station_layout:
            return

        pen = QPen(Qt.GlobalColor.lightGray)
        pen.setWidthF(1.0)
        pen.setStyle(Qt.PenStyle.DashLine)

        for name, x0, x1, _ in self._topo_station_layout:
            rep_node_id = self._station_rep_node_id.get(name)
            w = max(1.0, x1 - x0)
            rect = QGraphicsRectItem(QRectF(x0, -95.0, w, 190.0))
            rect.setPen(pen)
            rect.setBrush(QBrush(Qt.BrushStyle.NoBrush))
            rect.setZValue(-10)
            rect.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            if rep_node_id:
                rect.setData(1, rep_node_id)
                rect.setData(2, "stationRect")
            self._scene.addItem(rect)
            self._station_rect_items[name] = rect

            # Clickable marker dot on the baseline
            if rep_node_id:
                dot = QGraphicsEllipseItem(-6.0, -6.0, 12.0, 12.0)
                dot.setPos(QPointF(x0 + w / 2.0, 0.0))
                dot.setBrush(QBrush(Qt.GlobalColor.red))
                dot_pen = QPen(Qt.GlobalColor.black)
                dot_pen.setWidthF(1.0)
                dot.setPen(dot_pen)
                dot.setZValue(15)
                dot.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
                dot.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
                dot.setData(1, rep_node_id)
                dot.setData(2, "station")
                self._scene.addItem(dot)

            label_text = name
            if len(label_text) > 28:
                label_text = label_text[:25].rstrip() + "..."
            label = QGraphicsSimpleTextItem(label_text)
            label.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
            label.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations, True)
            if rep_node_id:
                label.setData(1, rep_node_id)
                label.setData(2, "station")
            br = label.boundingRect()
            label.setPos(QPointF(x0 + w / 2.0 - br.width() / 2.0, -118.0))
            label.setZValue(50)
            self._scene.addItem(label)

    def _add_topological_skeleton_edges(self) -> None:
        if not self._topo_station_layout:
            return

        by_comp: Dict[int, List[float]] = {}
        for _, x0, x1, comp_idx in self._topo_station_layout:
            by_comp.setdefault(comp_idx, []).append((x0 + x1) / 2.0)

        for comp_idx, centers in by_comp.items():
            centers.sort()
            for i, (a, b) in enumerate(zip(centers[:-1], centers[1:])):
                pts = [QPointF(a, 0.0), QPointF(b, 0.0)]
                pts = self._axis_polyline_with_45deg_corners(pts, bevel=24.0)
                path = self._path_from_points(pts)
                item = TrackItem(f"__topo_skeleton__:{comp_idx}:{i}", path)
                item.setAcceptHoverEvents(False)
                item.setAcceptedMouseButtons(Qt.MouseButton.NoButton)
                item.inner_overlay().setAcceptedMouseButtons(Qt.MouseButton.NoButton)
                item.inner_overlay().setAcceptHoverEvents(False)
                self._scene.addItem(item)
                self._scene.addItem(item.inner_overlay())

    def _node_sort_key(self, node_id: str) -> Tuple[float, str]:
        node = self._nodes.get(node_id)
        numeric = float(node.numeric_id) if node and node.numeric_id is not None else math.inf
        return numeric, node_id

    # --------------
    # View fitting
    # --------------

    def _scene_distance_for_view_pixels(self, px: float) -> float:
        t = self._view.transform()
        sx = abs(float(t.m11()))
        sy = abs(float(t.m22()))
        s = (sx + sy) / 2.0 if sx > 1e-9 and sy > 1e-9 else max(sx, sy, 1.0)
        if s <= 1e-9:
            return float(px)
        return float(px) / s

    def _dist_sq_point_to_segment(self, p: QPointF, a: QPointF, b: QPointF) -> float:
        ax = float(a.x())
        ay = float(a.y())
        bx = float(b.x())
        by = float(b.y())
        px = float(p.x())
        py = float(p.y())

        abx = bx - ax
        aby = by - ay
        apx = px - ax
        apy = py - ay
        ab_len_sq = abx * abx + aby * aby
        if ab_len_sq <= 1e-12:
            dx = px - ax
            dy = py - ay
            return dx * dx + dy * dy

        t = (apx * abx + apy * aby) / ab_len_sq
        if t <= 0.0:
            cx, cy = ax, ay
        elif t >= 1.0:
            cx, cy = bx, by
        else:
            cx = ax + t * abx
            cy = ay + t * aby
        dx = px - cx
        dy = py - cy
        return dx * dx + dy * dy

    def _min_dist_sq_to_polyline(self, p: QPointF, pts: List[QPointF]) -> float:
        if len(pts) < 2:
            dx = float(p.x() - pts[0].x())
            dy = float(p.y() - pts[0].y())
            return dx * dx + dy * dy

        best = float("inf")
        for a, b in zip(pts[:-1], pts[1:]):
            d = self._dist_sq_point_to_segment(p, a, b)
            if d < best:
                best = d
        return best

    def _pick_track_id_near(self, scene_pos: QPointF, tolerance_px: float = 8.0) -> Optional[str]:
        tol_scene = self._scene_distance_for_view_pixels(tolerance_px)
        tol_sq = tol_scene * tol_scene

        best_id: Optional[str] = None
        best_d = float("inf")
        for tr in self._tracks.values():
            pts = self._polyline_points_for_track(tr)
            if not pts:
                continue
            d = self._min_dist_sq_to_polyline(scene_pos, pts)
            if d <= tol_sq and d < best_d:
                best_d = d
                best_id = tr.id
        return best_id
