"""Internal mixin for InfrastructureView.

This file is generated by refactoring Source/InfrastructureView.py to keep the main widget
small and focused.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PyQt6.QtCore import Qt, QPointF, QRectF, QTimer, QEvent
from PyQt6.QtGui import QBrush, QColor, QPainterPath, QPen
from PyQt6.QtWidgets import (
    QDialog,
    QGraphicsEllipseItem,
    QGraphicsItem,
    QGraphicsPathItem,
    QGraphicsRectItem,
    QGraphicsSimpleTextItem,
    QGraphicsView,
    QMessageBox,
    QWidget,
)

from Source.infra_items import NodeItem, TrackItem, TimingPointItem, StoppingLocationItem
from Source.infra_models import Node, Track, TimingPoint, StoppingLocation, SchematicSegment
from Source.infra_ui import TimingConstraintDialog


class InfrastructureViewSettingsMixin:
    def _position_overlay_widgets(self) -> None:
        if getattr(self, "_legend", None) is None:
            return
        self._legend.adjustSize()
        self._legend.move(12, 12)
        self._legend.raise_()

    def _load_settings(self) -> None:
        settings_path = Path("user_settings.json")
        if settings_path.exists():
            try:
                with open(settings_path, "r") as f:
                    settings = json.load(f)
                    self._current_theme = settings.get("theme", "light")
                    self._show_all_tp = settings.get("show_all_tp", False)
                    self._keep_selection = settings.get("keep_selection", False)
                    self._show_legend = settings.get("show_legend", True)
                    self._default_view = settings.get("default_view", "Geographic")
                    
                    # Apply settings to UI
                    self._settings_view._theme_combo.setCurrentText(self._current_theme.capitalize())
                    self._settings_view._show_all_tp_check.setChecked(self._show_all_tp)
                    self._settings_view._keep_selection_check.setChecked(self._keep_selection)
                    self._settings_view._show_legend_check.setChecked(self._show_legend)
                    self._settings_view._default_view_combo.setCurrentText(self._default_view)
                    
                    # Apply to view
                    self._on_theme_changed(self._current_theme)
                    self._on_layout_mode_changed(self._default_view)
                    self._layout_combo.setCurrentText(self._default_view)
                    self._on_show_legend_changed(self._show_legend)
            except Exception as e:
                print(f"Failed to load settings: {e}")

    def _save_settings(self) -> None:
        settings = {
            "theme": self._current_theme,
            "show_all_tp": self._show_all_tp,
            "keep_selection": self._keep_selection,
            "show_legend": self._show_legend,
            "default_view": self._default_view
        }
        try:
            with open("user_settings.json", "w") as f:
                json.dump(settings, f)
        except Exception as e:
            print(f"Failed to save settings: {e}")

    def _on_theme_changed(self, theme: str) -> None:
        self._current_theme = theme
        self._save_settings()
        
        # Update view background
        if theme == "dark":
            self._view.setBackgroundBrush(QBrush(QColor(34, 34, 34)))
            self._legend.setStyleSheet(
                "QLabel {"
                " background: rgba(45, 45, 45, 230);"
                " border: 1px solid rgba(255, 255, 255, 70);"
                " border-radius: 6px;"
                " padding: 6px 8px;"
                " color: #eee;"
                " font-size: 11px;"
                "}"
            )
        else:
            self._view.setBackgroundBrush(QBrush(Qt.GlobalColor.white))
            self._legend.setStyleSheet(
                "QLabel {"
                " background: rgba(255, 255, 255, 230);"
                " border: 1px solid rgba(0, 0, 0, 70);"
                " border-radius: 6px;"
                " padding: 6px 8px;"
                " color: #111;"
                " font-size: 11px;"
                "}"
            )

        self._rebuild_scene()

    def _on_show_all_tp_changed(self, enabled: bool) -> None:
        self._show_all_tp = enabled
        self._save_settings()
        self._rebuild_scene() # Rebuild to apply visibility rules

    def _on_keep_selection_changed(self, enabled: bool) -> None:
        self._keep_selection = enabled
        self._save_settings()

    def _on_show_legend_changed(self, enabled: bool) -> None:
        self._show_legend = enabled
        self._legend.setVisible(enabled)
        self._save_settings()

    def _on_default_view_changed(self, view_name: str) -> None:
        self._default_view = view_name
        self._save_settings()

    def _update_legend_text(self) -> None:
        if getattr(self, "_legend", None) is None:
            return
        if self._layout_mode in {"topological", "plan"}:
            self._legend.setText(
                "<b>Legende</b><br>"
                "<span style='color:#000'>■</span> Gleis&nbsp;&nbsp;"
                "<span style='color:#00BCD4'>■</span> Route<br>"
                "<span style='color:#D32F2F'>●</span> Bahnhof<br><br>"
                "<b>Routenplanung</b><br>"
                "Klick: Start → Ziel (berechnet Route)<br>"
                "Shift+Klick: Zwischenhalt (Waypoint)<br>"
                "Klick nach fertiger Route: neue Route"
            )
        else:
            self._legend.setText(
                "<b>Legende</b><br>"
                "<span style='color:#606060'>■</span> Gleis&nbsp;&nbsp;"
                "<span style='color:#00008B'>■</span> Gleis (TPs an)&nbsp;&nbsp;"
                "<span style='color:#00BCD4'>■</span> Route<br>"
                "<span style='color:#1E90FF'>■</span> Hover&nbsp;&nbsp;"
                "<span style='color:#D32F2F'>●</span> Bahnhof/Node&nbsp;&nbsp;"
                "<span style='color:#1976D2'>●</span> Timing point&nbsp;&nbsp;"
                "<span style='color:#8B0000'>●</span> Halt"
            )
        self._position_overlay_widgets()

    def resizeEvent(self, event):
        # This is a mixin method; using `super()` here can skip the QWidget implementation
        # depending on the MRO. Call QWidget explicitly to ensure Qt's base handling runs.
        QWidget.resizeEvent(self, event)
        self._position_overlay_widgets()
        # Do the initial fit once, when the widget first gets a meaningful size.
        if not getattr(self, "_initial_fit_done", False):
            QTimer.singleShot(0, self._fit_to_scene)

    # -----------
    # Interaction / event filter
    # -----------
