"""Internal mixin for InfrastructureView.

This file is generated by refactoring Source/InfrastructureView.py to keep the main widget
small and focused.
"""

from __future__ import annotations

import json
from pathlib import Path

from PyQt6.QtCore import QTimer
from PyQt6.QtWidgets import QMessageBox

from Source.infra_data_manager import InfrastructureParser


class InfrastructureViewDataMixin:
    def _on_infrastructure_load_requested(self, json_path: str) -> None:
        try:
            self.load_infrastructure(json_path)
        except Exception as exc:
            self._parameter_view.set_infrastructure_error(json_path, str(exc))
            QMessageBox.critical(self, "Failed to load infrastructure", str(exc))
            return
        self._tabs.setCurrentIndex(0)

    def _on_parameters_changed(self, params: dict) -> None:
        self._parameters = dict(params or {})

    def load_infrastructure(self, json_path: str) -> None:
        """
        Load and render infrastructure from JSON file.
        """
        try:
            model = InfrastructureParser.parse_file(json_path)
        except Exception as e:
            raise e

        # Transfer data from model to self for compatibility with other mixins
        self._nodes = model.nodes
        self._tracks = model.tracks
        self._timing_points = model.timing_points
        self._stopping_locations = model.stopping_locations
        self._sl_to_group = model.sl_to_group
        self._simple_point_connections = model.simple_point_connections
        self._infrastructure_json_path = model.json_path
        
        # Reset selection states
        self._visible_tp_tracks.clear()
        self._timing_constraints.clear()

        self._build_graph()
        self._rebuild_scene()
        self.clear_route()
        self._initial_fit_done = False
        
        self._parameter_view.set_infrastructure_summary(
            json_path,
            nodes=len(self._nodes),
            tracks=len(self._tracks),
            timing_points=len(self._timing_points),
            stopping_locations=len(self._stopping_locations),
        )
        QTimer.singleShot(0, self._fit_to_scene)

    # -----------
    # Graph & routing
    # -----------
