"""Internal mixin for InfrastructureView.

This file is generated by refactoring Source/InfrastructureView.py to keep the main widget
small and focused.
"""

from __future__ import annotations

from typing import Dict, List, Tuple


class InfrastructureViewRoutingMixin:
    def _build_graph(self) -> None:
        """
        Undirected graph (physical tracks) with edge weight = track length.
        """
        self._graph = {nid: [] for nid in self._nodes.keys()}
        for tr in self._tracks.values():
            if tr.source not in self._nodes or tr.target not in self._nodes:
                continue
            w = tr.length_m if tr.length_m > 0 else 1.0
            self._graph[tr.source].append((tr.target, tr.id, w))
            self._graph[tr.target].append((tr.source, tr.id, w))

    def _shortest_path(self, start: str, goal: str) -> Tuple[List[str], List[str]]:
        """
        Dijkstra over nodes, returning (node_path, track_path).
        node_path includes both endpoints.
        """
        if start == goal:
            return [start], []

        import heapq
        dist: Dict[str, float] = {start: 0.0}
        prev: Dict[str, Tuple[str, str]] = {}  # node -> (prevNode, trackId)
        pq = [(0.0, start)]
        seen = set()

        while pq:
            d, u = heapq.heappop(pq)
            if u in seen:
                continue
            seen.add(u)
            if u == goal:
                break
            for v, track_id, w in self._graph.get(u, []):
                nd = d + w
                if nd < dist.get(v, float("inf")):
                    dist[v] = nd
                    prev[v] = (u, track_id)
                    heapq.heappush(pq, (nd, v))

        if goal not in prev and goal != start:
            return [start], []

        # reconstruct
        nodes = [goal]
        tracks = []
        cur = goal
        while cur != start:
            pu, tr_id = prev[cur]
            tracks.append(tr_id)
            nodes.append(pu)
            cur = pu
        nodes.reverse()
        tracks.reverse()
        return nodes, tracks

    def _extend_route_with_node(self, node_id: str) -> None:
        if node_id not in self._nodes:
            return

        if not self._route_node_ids:
            self._route_node_ids = [node_id]
            self._route_track_ids = []
        else:
            last = self._route_node_ids[-1]
            node_path, track_path = self._shortest_path(last, node_id)
            if len(node_path) <= 1:
                return
            # append, skipping the first because it's last
            self._route_node_ids.extend(node_path[1:])
            self._route_track_ids.extend(track_path)

        self._update_route_highlights()
        self.routeChanged.emit(list(self._route_node_ids))
