"""Internal mixin for InfrastructureView.

This file is generated by refactoring Source/InfrastructureView.py to keep the main widget
small and focused.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PyQt6.QtCore import Qt, QPointF, QRectF, QTimer, QEvent
from PyQt6.QtGui import QBrush, QColor, QPainterPath, QPen
from PyQt6.QtWidgets import (
    QDialog,
    QGraphicsEllipseItem,
    QGraphicsItem,
    QGraphicsPathItem,
    QGraphicsRectItem,
    QGraphicsSimpleTextItem,
    QGraphicsView,
    QMessageBox,
)

from Source.infra_items import NodeItem, TrackItem, TimingPointItem, StoppingLocationItem
from Source.infra_models import Node, Track, TimingPoint, StoppingLocation


class InfrastructureViewSceneMixin:
    def _on_layout_mode_changed(self, mode_text: str) -> None:
        lowered = mode_text.lower().strip()
        if lowered.startswith("schem") or lowered.startswith("topo"):
            mode = "topological"
        else:
            mode = "geographic"
        if mode == self._layout_mode:
            return
        self._layout_mode = mode
        self._rebuild_scene()
        self._update_legend_text()
        self._initial_fit_done = False
        QTimer.singleShot(0, self._fit_to_scene)

    # -----------
    # Loading
    # -----------

    def _rebuild_scene(self) -> None:
        self._scene.clear()
        self._node_items.clear()
        self._track_items.clear()
        self._tp_items.clear()
        self._sl_items.clear()
        self._tp_track_map.clear()
        self._track_render_paths.clear()
        self._track_render_polylines.clear()

        if self._layout_mode == "topological":
            self._rebuild_schematic_scene()
            return

        self._node_positions = self._compute_node_positions()

        # Tracks first
        for tr in self._tracks.values():
            path = self._track_to_path(tr)
            if path is None:
                continue
            item = TrackItem(tr.id, path)
            item.set_theme(self._current_theme)
            item.setAcceptHoverEvents(False)
            label = f"Track {tr.numeric_id}" if tr.numeric_id is not None else "Track"
            tip = f"{label}\nlen={tr.length_m:.0f} m\n{tr.id}"
            item.setToolTip(tip)
            item.inner_overlay().setToolTip(tip)
            item.route_overlay().setToolTip(tip)
            item.inner_overlay().setAcceptHoverEvents(False)
            item.route_overlay().setAcceptHoverEvents(False)
            item.set_timing_points_visible(self._show_all_tp or tr.id in self._visible_tp_tracks)
            self._scene.addItem(item)
            self._scene.addItem(item.inner_overlay())
            self._scene.addItem(item.route_overlay())
            self._track_items[tr.id] = item
            self._tp_track_map.setdefault(tr.id, [])

        # Nodes
        for node in self._nodes.values():
            pos = self._node_positions.get(node.id, QPointF(node.x, node.y))
            ni = NodeItem(node)
            ni.set_theme(self._current_theme)
            ni.setPos(pos)
            self._scene.addItem(ni)
            self._node_items[node.id] = ni

        # Timing points (blue)
        for tp in self._timing_points.values():
            pos = self._timing_point_position(tp)
            if pos is None:
                continue
            tpi = TimingPointItem(tp, pos)
            tpi.set_theme(self._current_theme)
            
            # Visibility logic:
            # 1. Show all TPs if setting is enabled.
            # 2. Show if track is selected.
            # 3. Show if it has a 'STOP' constraint (even if track unchecked).
            # 4. 'PASS' constraint should behave like normal (only visible if track is visible),
            #    unless show_all_tp is on.
            
            has_stop = False
            if tp.id in self._timing_constraints:
                c = self._timing_constraints[tp.id]
                if c.get("pointType") == "STOP":
                    has_stop = True

            is_visible = (
                self._show_all_tp 
                or (tp.track_id in self._visible_tp_tracks) 
                or has_stop
            )
            tpi.setVisible(is_visible)
            self._scene.addItem(tpi)
            self._tp_items[tp.id] = tpi
            self._tp_track_map.setdefault(tp.track_id, []).append(tpi)

        # Stopping locations + labels
        for sl in self._stopping_locations.values():
            pos = self._stopping_location_position(sl)
            if pos is None:
                continue

            group = self._sl_to_group.get(sl.id, "")
            suffix = ""
            if "-SL-" in sl.id:
                suffix = sl.id.split("-SL-")[-1].strip()
            label = group if group else sl.id
            if group and suffix:
                label = f"{group} {suffix}"

            sli = StoppingLocationItem(sl.id, pos, label)
            sli.set_theme(self._current_theme)
            self._scene.addItem(sli)
            self._scene.addItem(sli.label_item())
            self._sl_items[sl.id] = sli

        # Hook mouse events by installing a scene event filter
        # (We route clicks based on item types.)
        self._scene.installEventFilter(self)

        self._restore_timing_point_markers()
        self._update_route_highlights()

    def _rebuild_schematic_scene(self) -> None:
        """
        Schematic view is intentionally disabled.

        This project currently only supports the geographic rendering mode.
        """
        self._node_positions = {}
        self._scene.setSceneRect(QRectF(-1000.0, -1000.0, 2000.0, 2000.0))
        self._scene.installEventFilter(self)

    def _fit_to_scene(self) -> None:
        """Fit the view so the whole infrastructure is visible.

        We call this after the widget has a real size (QTimer.singleShot(0, ...)).
        """
        if self._view.viewport().width() <= 2 or self._view.viewport().height() <= 2:
            return

        items_rect = self._scene.itemsBoundingRect()
        if items_rect.isNull():
            return

        if self._layout_mode == "topological":
            # In schematic view, keep the baseline around y=0 visually centered and
            # give some extra scroll room so panning works even when zoomed out.
            pad_x = max(items_rect.width() * 0.06, 220.0)
            pad_y = max(items_rect.height() * 0.10, 220.0)
            fit_rect = items_rect.adjusted(-pad_x, -pad_y, pad_x, pad_y)

            half_y = max(abs(float(fit_rect.top())), abs(float(fit_rect.bottom())))
            half_y = max(half_y, float(fit_rect.height()) / 2.0)
            fit_rect = QRectF(fit_rect.left(), -half_y, fit_rect.width(), 2.0 * half_y)

            pan_pad = max(max(fit_rect.width(), fit_rect.height()) * 0.25, 420.0)
            scene_rect = fit_rect.adjusted(-pan_pad, -pan_pad, pan_pad, pan_pad)
        else:
            pad = max(items_rect.width(), items_rect.height()) * 0.02  # 2%
            pad = max(pad, 20.0)
            fit_rect = items_rect.adjusted(-pad, -pad, pad, pad)
            scene_rect = fit_rect

        self._scene.setSceneRect(scene_rect)

        prev_anchor = self._view.transformationAnchor()
        prev_resize_anchor = self._view.resizeAnchor()
        self._view.setTransformationAnchor(QGraphicsView.ViewportAnchor.AnchorViewCenter)
        self._view.setResizeAnchor(QGraphicsView.ViewportAnchor.AnchorViewCenter)
        self._view.resetTransform()
        self._view.fitInView(fit_rect, Qt.AspectRatioMode.KeepAspectRatio)
        self._view.centerOn(fit_rect.center())
        self._view.setTransformationAnchor(prev_anchor)
        self._view.setResizeAnchor(prev_resize_anchor)
        self._initial_fit_done = True
