"""Internal mixin for InfrastructureView.

This file is generated by refactoring Source/InfrastructureView.py to keep the main widget
small and focused.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PyQt6.QtCore import Qt, QPointF, QRectF, QTimer, QEvent
from PyQt6.QtGui import QBrush, QColor, QPainterPath, QPen
from PyQt6.QtWidgets import (
    QDialog,
    QGraphicsEllipseItem,
    QGraphicsItem,
    QGraphicsPathItem,
    QGraphicsRectItem,
    QGraphicsSimpleTextItem,
    QGraphicsView,
    QMessageBox,
    QWidget,
)

from Source.infra_items import NodeItem, TrackItem, TimingPointItem, StoppingLocationItem
from Source.infra_models import Node, Track, TimingPoint, StoppingLocation, SchematicSegment
from Source.infra_ui import TimingConstraintDialog


class InfrastructureViewInteractionMixin:
    def _set_hovered_track(self, track_id: Optional[str]) -> None:
        prev = getattr(self, "_hover_track_id", None)
        if prev == track_id:
            return
        if isinstance(prev, str):
            prev_item = self._track_items.get(prev)
            if prev_item:
                prev_item.set_hover_highlight(False)
        if isinstance(track_id, str):
            item = self._track_items.get(track_id)
            if item:
                item.set_hover_highlight(True)
        self._hover_track_id = track_id

    def _can_start_background_pan(self, scene_pos: QPointF) -> bool:
        if self._layout_mode in {"topological", "plan"}:
            for cand in self._scene.items(scene_pos):
                if cand.data(2) == "station":
                    return False
                top = cand.topLevelItem()
                if isinstance(top, NodeItem):
                    return False
            return True

        for cand in self._scene.items(scene_pos):
            top = cand.topLevelItem()
            if isinstance(top, (TimingPointItem, NodeItem)):
                return False

        return self._pick_track_id_near(scene_pos) is None

    def _track_id_from_item(self, item: Optional[QGraphicsItem]) -> Optional[str]:
        if item is None:
            return None
        if isinstance(item, TrackItem):
            return item.track_id
        data = item.data(0)
        if isinstance(data, str) and data in self._tracks:
            return data
        return None

    def _toggle_track_timing_points(self, track_id: str) -> None:
        if not self._keep_selection and track_id not in self._visible_tp_tracks:
            # If not keeping selection and clicking a new track, clear others.
            # But we must be careful: if we just clear, we lose the toggle logic.
            # The user said: "You click on another track and the timing points that were previously selected on another track will disappear."
            # This implies if I select A, then select B, A should deselect.
            # If I select A, then select A again, A should deselect.
            old_visible = list(self._visible_tp_tracks)
            self._visible_tp_tracks.clear()
            for old_id in old_visible:
                self._apply_track_tp_visibility(old_id, False)

        visible = track_id not in self._visible_tp_tracks
        if visible:
            self._visible_tp_tracks.add(track_id)
        else:
            self._visible_tp_tracks.discard(track_id)
        self._apply_track_tp_visibility(track_id, visible)

    def _apply_track_tp_visibility(self, track_id: str, visible: bool) -> None:
        for tpi in self._tp_track_map.get(track_id, []):
            # Check for STOP constraint
            has_stop = False
            if tpi.tp.id in self._timing_constraints:
                c = self._timing_constraints[tpi.tp.id]
                if c.get("pointType") == "STOP":
                    has_stop = True
            
            should_show = self._show_all_tp or visible or has_stop
            tpi.setVisible(should_show)
            
            if not should_show:
                tpi.setSelected(False)
                
        track_item = self._track_items.get(track_id)
        if track_item:
            track_item.set_timing_points_visible(visible)

    def eventFilter(self, obj, event):
        if obj is self._scene:
            if event.type() == QEvent.Type.GraphicsSceneMouseMove:
                # Stable hover highlighting in geographic mode.
                # Qt's default hit-testing can feel "off" with thick multi-stroke track rendering,
                # so we explicitly pick the closest track within a small screen-space tolerance.
                if self._layout_mode not in {"geographic"}:
                    self._set_hovered_track(None)
                elif event.buttons() == Qt.MouseButton.NoButton:
                    tol_px = 4.0
                    tol_scene = self._scene_distance_for_view_pixels(tol_px)
                    tol_sq = tol_scene * tol_scene

                    hovered: Optional[str] = None
                    for cand in self._scene.items(event.scenePos()):
                        tid = self._track_id_from_item(cand.topLevelItem())
                        if not tid:
                            continue
                        pts = self._polyline_points_for_track(self._tracks[tid])
                        if not pts:
                            continue
                        d = self._min_dist_sq_to_polyline(event.scenePos(), pts)
                        if d <= tol_sq:
                            hovered = tid
                            break

                    if hovered is None:
                        hovered = self._pick_track_id_near(event.scenePos(), tolerance_px=tol_px)
                    self._set_hovered_track(hovered)

            if event.type() == QEvent.Type.GraphicsSceneMousePress:
                if self._layout_mode in {"topological", "plan"} and event.button() == Qt.MouseButton.LeftButton:
                    for cand in self._scene.items(event.scenePos()):
                        if cand.data(2) != "station":
                            continue
                        rep = cand.data(1)
                        if isinstance(rep, str):
                            self._handle_planning_station_click(rep, modifiers=event.modifiers())
                            return True

                item: Optional[QGraphicsItem] = None
                for cand in self._scene.items(event.scenePos()):
                    top = cand.topLevelItem()
                    if isinstance(top, (TimingPointItem, NodeItem)):
                        item = top
                        break

                # Timing point interactions
                if isinstance(item, TimingPointItem):
                    if event.button() == Qt.MouseButton.LeftButton:
                        self._edit_timing_constraint(item.tp.id)
                        return True
                    if event.button() == Qt.MouseButton.RightButton:
                        self._remove_timing_constraint(item.tp.id)
                        return True

                # Route selection
                if isinstance(item, NodeItem):
                    if event.button() == Qt.MouseButton.LeftButton:
                        # In plan/topological mode we plan station-to-station via click targets.
                        if self._layout_mode in {"topological", "plan"}:
                            return False
                        self._extend_route_with_node(item.node.id)
                        return True

                if event.button() == Qt.MouseButton.LeftButton:
                    track_id = self._pick_track_id_near(event.scenePos())
                else:
                    track_id = None

                if self._layout_mode not in {"topological", "plan"} and track_id and event.button() == Qt.MouseButton.LeftButton:
                    self._toggle_track_timing_points(track_id)
                    return True

                # Clicking empty space does nothing special.

        # This is a mixin method; `super()` may not reach QWidget depending on the MRO.
        return QWidget.eventFilter(self, obj, event)

    def _on_selection_changed(self) -> None:
        sel = self._scene.selectedItems()
        if not sel:
            self.selectionChanged.emit({})
            return

        item = sel[0]
        info: Dict[str, Any] = {}
        if isinstance(item, NodeItem):
            info = {"type": "node", "id": item.node.id, "numericId": item.node.numeric_id}
        elif isinstance(item, TimingPointItem):
            info = {
                "type": "timingPoint",
                "id": item.tp.id,
                "trackId": item.tp.track_id,
                "targetNodeId": item.tp.target_node_id,
            }
        self.selectionChanged.emit(info)

    # -----------
    # Route selection
    # -----------

    def clear_route(self) -> None:
        self._route_node_ids = []
        self._route_track_ids = []
        self._route_plan_start = None
        self._route_plan_goal = None
        self._route_plan_waypoints = []
        self._update_route_highlights()
        self._update_planning_status_labels()
        self.routeChanged.emit(list(self._route_node_ids))

    def _update_route_highlights(self) -> None:
        route_nodes = set(self._route_node_ids)
        route_tracks = set(self._route_track_ids)

        for nid, item in self._node_items.items():
            item.set_highlight(nid in route_nodes)

        for tid, item in self._track_items.items():
            if self._layout_mode in {"topological", "plan"}:
                seg = self._schem_segments.get(tid)
                enabled = bool(seg) and any(orig_tid in route_tracks for orig_tid in seg.track_ids)
            else:
                enabled = tid in route_tracks
            item.set_route_highlight(enabled)

    def _update_topological_route_overlay(self) -> None:
        default_pen = QPen(Qt.GlobalColor.lightGray)
        default_pen.setWidthF(1.0)
        default_pen.setStyle(Qt.PenStyle.DashLine)
        highlight_pen = QPen(Qt.GlobalColor.darkCyan)
        highlight_pen.setWidthF(2.0)
        highlight_pen.setStyle(Qt.PenStyle.SolidLine)

        for rect in self._station_rect_items.values():
            rect.setPen(default_pen)

        route_stations: List[str] = []
        for nid in self._route_node_ids:
            s = self._node_to_station.get(nid)
            if not s:
                continue
            if not route_stations or route_stations[-1] != s:
                route_stations.append(s)

        for s in route_stations:
            rect = self._station_rect_items.get(s)
            if rect:
                rect.setPen(highlight_pen)

        if self._topo_route_item is None:
            return

        centers = {name: (x0 + x1) / 2.0 for (name, x0, x1, _) in self._topo_station_layout}
        pts = [QPointF(centers[s], 0.0) for s in route_stations if s in centers]
        if len(pts) < 2:
            self._topo_route_item.setPath(QPainterPath())
            return

        pts = self._axis_polyline_with_45deg_corners(pts, bevel=24.0)
        path = self._path_from_points(pts)
        self._topo_route_item.setPath(path)

    def _restore_timing_point_markers(self) -> None:
        for tp_id, constraint in self._timing_constraints.items():
            item = self._tp_items.get(tp_id)
            if item:
                item.set_constraint_point_type(constraint.get("pointType"))
                item.setVisible(True)

    # -----------
    # Timing constraints
    # -----------

    def _edit_timing_constraint(self, tp_id: int) -> None:
        tp = self._timing_points.get(tp_id)
        if tp is None:
            return

        existing = self._timing_constraints.get(tp_id)
        dlg = TimingConstraintDialog(self, tp_id, existing=existing)
        if dlg.exec() != QDialog.DialogCode.Accepted:
            return

        c = dlg.result_constraint()
        # Treat "PASS with no times" as default (i.e. no constraint).
        if c.get("pointType") == "PASS" and not c.get("arrivalTime") and not c.get("departureTime"):
            self._remove_timing_constraint(tp_id)
            return
        constraint = {
            "timingPointId": tp_id,
            "trackId": tp.track_id,
            "targetNodeId": tp.target_node_id,
            "distanceToTargetNodeInMeters": tp.distance_to_target_m,
            "pointType": c["pointType"],
            "arrivalTime": c["arrivalTime"],
            "departureTime": c["departureTime"],
        }
        self._timing_constraints[tp_id] = constraint

        item = self._tp_items.get(tp_id)
        if item:
            item.set_constraint_point_type(c["pointType"])
            # Re-apply visibility logic because changing STOP <-> PASS affects visibility
            # when the track is hidden.
            # We know the track ID is tp.track_id.
            is_track_visible = tp.track_id in self._visible_tp_tracks
            self._apply_track_tp_visibility(tp.track_id, is_track_visible)

        self.timingConstraintsChanged.emit(self.timing_constraints())

    def _remove_timing_constraint(self, tp_id: int) -> None:
        if tp_id not in self._timing_constraints:
            return
        
        # Capture track ID before deleting
        track_id = self._timing_constraints[tp_id]["trackId"]
        
        del self._timing_constraints[tp_id]
        item = self._tp_items.get(tp_id)
        if item:
            item.set_constraint_point_type(None)
            # Re-apply visibility
            is_track_visible = track_id in self._visible_tp_tracks
            self._apply_track_tp_visibility(track_id, is_track_visible)
            
        self.timingConstraintsChanged.emit(self.timing_constraints())

    def timing_constraints(self) -> List[dict]:
        return [self._timing_constraints[k] for k in sorted(self._timing_constraints.keys())]

    # -----------
    # Export
    # -----------

    def export_state(self) -> dict:
        return {
            "infrastructureJsonPath": self._infrastructure_json_path,
            "parameters": dict(self._parameters),
            "routeNodeIds": list(self._route_node_ids),
            "timingConstraints": self.timing_constraints(),
        }
